name: Create Release on Tag Push

on:
  push:
    tags:
      - "*" # Trigger on any tag being pushed

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tag = context.payload.ref.split('/').pop();
            try {
              await github.rest.repos.createRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: tag,
                name: tag,
                body: '',
                draft: false,
                prerelease: tag.includes('-alpha') || tag.includes('-beta') || tag.includes('-rc'),
                generate_release_notes: true
              });
            } catch (error) {
              console.error('Failed to create release:', error);
            }
